# Generated by Django 3.2 on 2021-05-17 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0130_sitegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('status', models.CharField(default='1', max_length=20)),
                ('config', models.TextField(blank=True)),
                ('config_log', models.JSONField()),
                ('diff', models.TextField(blank=True)),
                ('compare_log', models.JSONField()),
                ('deployment_log', models.JSONField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.device')),
            ],
        ),
    ]
