# Generated by Django 3.2 on 2021-05-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_config_plugin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configjob',
            name='status',
        ),
        migrations.AddField(
            model_name='configjob',
            name='compare_status',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='configjob',
            name='config_status',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='configjob',
            name='deployment_status',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='configjob',
            name='compare_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='configjob',
            name='config_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='configjob',
            name='deployment_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
