# Generated by Django 3.2 on 2021-05-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_config_plugin', '0002_auto_20210517_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='configjob',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='configjob',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='configjob',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
